import React, { useMemo } from 'react';
import {
    View,
    Text,
    StyleSheet,
    ScrollView,
    TouchableOpacity,
    SafeAreaView,
    StatusBar,
    Share,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { useRouter, useLocalSearchParams } from 'expo-router';

import Card from '../components/Card';
import { colors, gradients, typography, spacing, borderRadius, shadows } from '../theme';

export default function DoctorSummary() {
    const router = useRouter();
    const { summary: summaryParam } = useLocalSearchParams();

    const summary = useMemo(() => {
        if (!summaryParam) return null;
        try {
            return JSON.parse(summaryParam);
        } catch {
            return null;
        }
    }, [summaryParam]);

    // Extract data from the DoctorReport structure
    const reportMetadata = summary?.report_metadata;
    const patientSummary = summary?.patient_summary;
    const symptomOverview = summary?.symptom_overview;
    const patterns = summary?.patterns;
    const severityTimeline = summary?.severity_timeline;
    const clinicalAlerts = summary?.clinical_alerts;
    const recommendedFollowups = summary?.recommended_followups;

    const getSeverityColor = (severity) => {
        if (severity <= 2) return colors.success;
        if (severity <= 3) return colors.warning;
        return colors.error;
    };

    const getTrendIcon = (trend) => {
        switch (trend) {
            case 'increasing':
                return { name: 'trending-up', color: colors.error };
            case 'decreasing':
                return { name: 'trending-down', color: colors.success };
            default:
                return { name: 'remove', color: colors.dustyPurple };
        }
    };

    const handleShare = async () => {
        try {
            const shareText = generateShareText();
            await Share.share({
                message: shareText,
                title: 'Doctor Summary Report',
            });
        } catch (err) {
            console.log('Share failed:', err);
        }
    };

    const generateShareText = () => {
        let text = `SYMPTOM SUMMARY REPORT\n`;
        text += `Generated: ${reportMetadata?.generated_at ? new Date(reportMetadata.generated_at).toLocaleDateString() : 'Today'}\n`;
        text += `Period: Last ${reportMetadata?.report_period_days || 30} days\n\n`;

        if (clinicalAlerts && clinicalAlerts.length > 0) {
            text += `⚠️ CLINICAL ALERTS:\n`;
            clinicalAlerts.forEach(a => text += `• ${a}\n`);
            text += '\n';
        }

        if (symptomOverview?.summaries) {
            text += `SYMPTOM OVERVIEW:\n`;
            text += `Total Logged: ${symptomOverview.total_logged}\n`;
            text += `Unique Types: ${symptomOverview.unique_types}\n\n`;
            
            symptomOverview.summaries.slice(0, 5).forEach(s => {
                text += `${s.symptom.toUpperCase()}\n`;
                text += `  Occurrences: ${s.occurrences} | Avg Severity: ${s.avg_severity}/5 | ${s.trend}\n`;
            });
            text += '\n';
        }

        if (recommendedFollowups && recommendedFollowups.length > 0) {
            text += `RECOMMENDED FOLLOW-UPS:\n`;
            recommendedFollowups.forEach(r => text += `• ${r}\n`);
        }

        text += '\n---\nGenerated by CareNest';
        return text;
    };

    if (!summary) {
        return (
            <LinearGradient colors={gradients.background} style={styles.container}>
                <SafeAreaView style={styles.safeArea}>
                    <View style={styles.errorContainer}>
                        <Ionicons name="alert-circle" size={48} color={colors.error} />
                        <Text style={styles.errorText}>Failed to load summary</Text>
                        <TouchableOpacity onPress={() => router.back()} style={styles.backLink}>
                            <Text style={styles.backLinkText}>Go Back</Text>
                        </TouchableOpacity>
                    </View>
                </SafeAreaView>
            </LinearGradient>
        );
    }

    return (
        <LinearGradient colors={gradients.background} style={styles.container}>
            <StatusBar barStyle="dark-content" />
            <SafeAreaView style={styles.safeArea}>
                <ScrollView
                    style={styles.scrollView}
                    contentContainerStyle={styles.scrollContent}
                    showsVerticalScrollIndicator={false}
                >
                    {/* Header */}
                    <View style={styles.header}>
                        <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
                            <Ionicons name="arrow-back" size={24} color={colors.inkPurple} />
                        </TouchableOpacity>
                        <Text style={styles.title}>Doctor Summary</Text>
                        <TouchableOpacity onPress={handleShare} style={styles.shareButton}>
                            <Ionicons name="share-outline" size={24} color={colors.neonPurple} />
                        </TouchableOpacity>
                    </View>

                    {/* Report Metadata Card */}
                    <Card style={styles.metadataCard}>
                        <View style={styles.metadataRow}>
                            <View style={styles.metadataItem}>
                                <Ionicons name="calendar" size={20} color={colors.neonPurple} />
                                <Text style={styles.metadataLabel}>Period</Text>
                                <Text style={styles.metadataValue}>
                                    {reportMetadata?.report_period_days || 30} days
                                </Text>
                            </View>
                            <View style={styles.metadataItem}>
                                <Ionicons name="analytics" size={20} color={colors.success} />
                                <Text style={styles.metadataLabel}>Data Quality</Text>
                                <Text style={styles.metadataValue}>
                                    {Math.round((reportMetadata?.data_quality_score || 0) * 100)}%
                                </Text>
                            </View>
                            <View style={styles.metadataItem}>
                                <Ionicons name="time" size={20} color={colors.softBlue} />
                                <Text style={styles.metadataLabel}>Generated</Text>
                                <Text style={styles.metadataValue}>
                                    {reportMetadata?.generated_at 
                                        ? new Date(reportMetadata.generated_at).toLocaleDateString()
                                        : 'Today'}
                                </Text>
                            </View>
                        </View>
                    </Card>

                    {/* Clinical Alerts - Prominent at top */}
                    {clinicalAlerts && clinicalAlerts.length > 0 && (
                        <Card style={styles.alertsCard}>
                            <View style={styles.alertsHeader}>
                                <Ionicons name="warning" size={22} color={colors.error} />
                                <Text style={styles.alertsTitle}>Clinical Alerts</Text>
                            </View>
                            {clinicalAlerts.map((alert, index) => (
                                <View key={index} style={styles.alertItem}>
                                    <Ionicons name="alert-circle" size={16} color={colors.error} />
                                    <Text style={styles.alertText}>{alert}</Text>
                                </View>
                            ))}
                        </Card>
                    )}

                    {/* Patient Context */}
                    {patientSummary && Object.keys(patientSummary).length > 0 && (
                        <Card style={styles.patientCard}>
                            <Text style={styles.sectionTitle}>Patient Context</Text>
                            <View style={styles.patientGrid}>
                                {patientSummary.age && (
                                    <View style={styles.patientItem}>
                                        <Text style={styles.patientLabel}>Age</Text>
                                        <Text style={styles.patientValue}>{patientSummary.age}</Text>
                                    </View>
                                )}
                                {patientSummary.pregnancy_stage && (
                                    <View style={styles.patientItem}>
                                        <Text style={styles.patientLabel}>Stage</Text>
                                        <Text style={styles.patientValue}>{patientSummary.pregnancy_stage}</Text>
                                    </View>
                                )}
                                {patientSummary.risk_level && (
                                    <View style={styles.patientItem}>
                                        <Text style={styles.patientLabel}>Risk Level</Text>
                                        <Text style={[
                                            styles.patientValue,
                                            patientSummary.risk_level === 'high' && { color: colors.error }
                                        ]}>
                                            {patientSummary.risk_level}
                                        </Text>
                                    </View>
                                )}
                            </View>
                            {patientSummary.known_conditions?.length > 0 && (
                                <View style={styles.conditionsList}>
                                    <Text style={styles.conditionsLabel}>Known Conditions:</Text>
                                    <Text style={styles.conditionsText}>
                                        {patientSummary.known_conditions.join(', ')}
                                    </Text>
                                </View>
                            )}
                        </Card>
                    )}

                    {/* Symptom Overview */}
                    {symptomOverview && (
                        <View style={styles.section}>
                            <View style={styles.sectionHeader}>
                                <Text style={styles.sectionTitle}>Symptom Overview</Text>
                                <View style={styles.overviewBadges}>
                                    <View style={styles.badge}>
                                        <Text style={styles.badgeValue}>{symptomOverview.total_logged}</Text>
                                        <Text style={styles.badgeLabel}>logged</Text>
                                    </View>
                                    <View style={styles.badge}>
                                        <Text style={styles.badgeValue}>{symptomOverview.unique_types}</Text>
                                        <Text style={styles.badgeLabel}>types</Text>
                                    </View>
                                </View>
                            </View>

                            {symptomOverview.summaries?.map((symptom, index) => {
                                const trendInfo = getTrendIcon(symptom.trend);
                                return (
                                    <Card key={index} style={styles.symptomCard}>
                                        <View style={styles.symptomHeader}>
                                            <View style={[styles.severityDot, { backgroundColor: getSeverityColor(symptom.avg_severity) }]} />
                                            <Text style={styles.symptomName}>{symptom.symptom}</Text>
                                            <View style={styles.trendBadge}>
                                                <Ionicons name={trendInfo.name} size={14} color={trendInfo.color} />
                                                <Text style={[styles.trendText, { color: trendInfo.color }]}>
                                                    {symptom.trend}
                                                </Text>
                                            </View>
                                        </View>

                                        <View style={styles.symptomStats}>
                                            <View style={styles.symptomStat}>
                                                <Text style={styles.symptomStatValue}>{symptom.occurrences}</Text>
                                                <Text style={styles.symptomStatLabel}>times</Text>
                                            </View>
                                            <View style={styles.symptomStat}>
                                                <Text style={styles.symptomStatValue}>{symptom.avg_severity}/5</Text>
                                                <Text style={styles.symptomStatLabel}>severity</Text>
                                            </View>
                                            <View style={styles.symptomStat}>
                                                <Text style={styles.symptomStatValue}>{symptom.weekly_frequency}/wk</Text>
                                                <Text style={styles.symptomStatLabel}>frequency</Text>
                                            </View>
                                        </View>

                                        {symptom.context && symptom.context.length > 0 && (
                                            <View style={styles.contextRow}>
                                                <Ionicons name="information-circle" size={14} color={colors.dustyPurple} />
                                                <Text style={styles.contextText}>
                                                    Associated with: {symptom.context.join(', ')}
                                                </Text>
                                            </View>
                                        )}

                                        <Text style={styles.symptomPeriod}>{symptom.period}</Text>
                                    </Card>
                                );
                            })}
                        </View>
                    )}

                    {/* Detected Patterns */}
                    {patterns?.key_patterns && patterns.key_patterns.length > 0 && (
                        <View style={styles.section}>
                            <Text style={styles.sectionTitle}>Detected Patterns</Text>
                            <Card style={styles.patternsCard}>
                                {patterns.key_patterns.map((pattern, index) => (
                                    <View key={index} style={styles.patternItem}>
                                        <View style={styles.patternIcon}>
                                            <Ionicons name="git-branch" size={16} color={colors.neonPurple} />
                                        </View>
                                        <View style={styles.patternContent}>
                                            <Text style={styles.patternType}>{pattern.pattern_type}</Text>
                                            <Text style={styles.patternDesc}>{pattern.description}</Text>
                                            {pattern.confidence && (
                                                <Text style={styles.patternConfidence}>
                                                    Confidence: {Math.round(pattern.confidence * 100)}%
                                                </Text>
                                            )}
                                        </View>
                                    </View>
                                ))}
                            </Card>
                        </View>
                    )}

                    {/* Symptom Clusters */}
                    {patterns?.symptom_clusters && patterns.symptom_clusters.length > 0 && (
                        <View style={styles.section}>
                            <Text style={styles.sectionTitle}>Symptom Clusters</Text>
                            <Text style={styles.sectionSubtitle}>Symptoms that tend to occur together</Text>
                            {patterns.symptom_clusters.map((cluster, index) => (
                                <Card key={index} style={styles.clusterCard}>
                                    <View style={styles.clusterSymptoms}>
                                        {cluster.symptoms?.map((symptom, i) => (
                                            <View key={i} style={styles.clusterChip}>
                                                <Text style={styles.clusterChipText}>{symptom}</Text>
                                            </View>
                                        ))}
                                    </View>
                                    <Text style={styles.clusterCount}>
                                        Co-occurred {cluster.co_occurrence_count} times
                                    </Text>
                                </Card>
                            ))}
                        </View>
                    )}

                    {/* Severity Timeline */}
                    {severityTimeline && severityTimeline.length > 0 && (
                        <View style={styles.section}>
                            <Text style={styles.sectionTitle}>Weekly Severity Timeline</Text>
                            <Card style={styles.timelineCard}>
                                {severityTimeline.map((week, index) => (
                                    <View key={index} style={styles.timelineRow}>
                                        <Text style={styles.timelineWeek}>{week.week_start}</Text>
                                        <View style={styles.timelineBar}>
                                            <View 
                                                style={[
                                                    styles.timelineBarFill,
                                                    { 
                                                        width: `${(week.avg_severity / 5) * 100}%`,
                                                        backgroundColor: getSeverityColor(week.avg_severity)
                                                    }
                                                ]} 
                                            />
                                        </View>
                                        <Text style={styles.timelineSeverity}>{week.avg_severity}</Text>
                                        <Text style={styles.timelineCount}>({week.symptom_count})</Text>
                                    </View>
                                ))}
                            </Card>
                        </View>
                    )}

                    {/* Recommended Follow-ups */}
                    {recommendedFollowups && recommendedFollowups.length > 0 && (
                        <View style={styles.section}>
                            <Text style={styles.sectionTitle}>Recommended Follow-ups</Text>
                            <Card style={styles.followupsCard}>
                                {recommendedFollowups.map((rec, index) => (
                                    <View key={index} style={styles.followupItem}>
                                        <View style={styles.followupIcon}>
                                            <Ionicons name="checkmark-circle" size={18} color={colors.success} />
                                        </View>
                                        <Text style={styles.followupText}>{rec}</Text>
                                    </View>
                                ))}
                            </Card>
                        </View>
                    )}

                    {/* Disclaimer */}
                    <Card style={styles.disclaimerCard}>
                        <Ionicons name="information-circle" size={18} color={colors.dustyPurple} />
                        <Text style={styles.disclaimerText}>
                            This report is generated from patient-reported symptoms and should be reviewed 
                            in context of clinical examination.
                        </Text>
                    </Card>

                    <View style={{ height: spacing.xxl }} />
                </ScrollView>
            </SafeAreaView>
        </LinearGradient>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    safeArea: {
        flex: 1,
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        padding: spacing.lg,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: spacing.lg,
        marginTop: spacing.md,
    },
    backButton: {
        padding: spacing.sm,
    },
    shareButton: {
        padding: spacing.sm,
    },
    title: {
        ...typography.h2,
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: spacing.xl,
    },
    errorText: {
        ...typography.h3,
        color: colors.error,
        marginTop: spacing.md,
    },
    backLink: {
        marginTop: spacing.lg,
    },
    backLinkText: {
        ...typography.body,
        color: colors.neonPurple,
    },

    // Metadata Card
    metadataCard: {
        padding: spacing.lg,
        marginBottom: spacing.lg,
    },
    metadataRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
    },
    metadataItem: {
        alignItems: 'center',
    },
    metadataLabel: {
        ...typography.caption,
        marginTop: spacing.xs,
    },
    metadataValue: {
        ...typography.h3,
        color: colors.inkPurple,
    },

    // Alerts Card
    alertsCard: {
        padding: spacing.lg,
        marginBottom: spacing.lg,
        backgroundColor: colors.error + '10',
        borderColor: colors.error + '30',
        borderWidth: 1,
    },
    alertsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.sm,
        marginBottom: spacing.md,
    },
    alertsTitle: {
        ...typography.h3,
        color: colors.error,
    },
    alertItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: spacing.sm,
        marginBottom: spacing.sm,
    },
    alertText: {
        ...typography.body,
        flex: 1,
        color: colors.inkPurple,
    },

    // Patient Card
    patientCard: {
        padding: spacing.lg,
        marginBottom: spacing.lg,
    },
    patientGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.md,
        marginTop: spacing.sm,
    },
    patientItem: {
        backgroundColor: colors.lightOrchid + '40',
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        borderRadius: borderRadius.sm,
    },
    patientLabel: {
        ...typography.caption,
    },
    patientValue: {
        ...typography.body,
        fontWeight: '600',
        textTransform: 'capitalize',
    },
    conditionsList: {
        marginTop: spacing.md,
        paddingTop: spacing.md,
        borderTopWidth: 1,
        borderTopColor: colors.lightOrchid,
    },
    conditionsLabel: {
        ...typography.caption,
        marginBottom: spacing.xs,
    },
    conditionsText: {
        ...typography.body,
    },

    // Section
    section: {
        marginBottom: spacing.lg,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: spacing.md,
    },
    sectionTitle: {
        ...typography.h3,
        marginBottom: spacing.sm,
    },
    sectionSubtitle: {
        ...typography.caption,
        marginTop: -spacing.xs,
        marginBottom: spacing.md,
    },
    overviewBadges: {
        flexDirection: 'row',
        gap: spacing.sm,
    },
    badge: {
        backgroundColor: colors.neonPurple + '20',
        paddingHorizontal: spacing.sm,
        paddingVertical: spacing.xs,
        borderRadius: borderRadius.sm,
        alignItems: 'center',
    },
    badgeValue: {
        ...typography.body,
        fontWeight: '700',
        color: colors.neonPurple,
    },
    badgeLabel: {
        ...typography.caption,
        fontSize: 10,
    },

    // Symptom Card
    symptomCard: {
        padding: spacing.md,
        marginBottom: spacing.sm,
    },
    symptomHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.sm,
    },
    severityDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
        marginRight: spacing.sm,
    },
    symptomName: {
        ...typography.body,
        fontWeight: '600',
        textTransform: 'capitalize',
        flex: 1,
    },
    trendBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: spacing.sm,
        paddingVertical: 2,
        backgroundColor: colors.lightOrchid + '50',
        borderRadius: borderRadius.sm,
    },
    trendText: {
        ...typography.caption,
        textTransform: 'capitalize',
    },
    symptomStats: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginVertical: spacing.sm,
        paddingVertical: spacing.sm,
        backgroundColor: colors.white,
        borderRadius: borderRadius.sm,
    },
    symptomStat: {
        alignItems: 'center',
    },
    symptomStatValue: {
        ...typography.h3,
        color: colors.neonPurple,
    },
    symptomStatLabel: {
        ...typography.caption,
        fontSize: 10,
    },
    contextRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: spacing.xs,
        marginTop: spacing.sm,
    },
    contextText: {
        ...typography.caption,
        flex: 1,
        fontStyle: 'italic',
    },
    symptomPeriod: {
        ...typography.caption,
        marginTop: spacing.sm,
        color: colors.dustyPurple,
    },

    // Patterns Card
    patternsCard: {
        padding: spacing.lg,
    },
    patternItem: {
        flexDirection: 'row',
        marginBottom: spacing.md,
    },
    patternIcon: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: colors.neonPurple + '20',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: spacing.sm,
    },
    patternContent: {
        flex: 1,
    },
    patternType: {
        ...typography.body,
        fontWeight: '600',
        textTransform: 'capitalize',
    },
    patternDesc: {
        ...typography.bodySmall,
        color: colors.mutedPurple,
        marginTop: 2,
    },
    patternConfidence: {
        ...typography.caption,
        marginTop: spacing.xs,
        color: colors.success,
    },

    // Cluster Card
    clusterCard: {
        padding: spacing.md,
        marginBottom: spacing.sm,
    },
    clusterSymptoms: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.xs,
    },
    clusterChip: {
        backgroundColor: colors.neonPurple + '20',
        paddingHorizontal: spacing.sm,
        paddingVertical: spacing.xs,
        borderRadius: borderRadius.full,
    },
    clusterChipText: {
        ...typography.caption,
        color: colors.neonPurple,
        textTransform: 'capitalize',
    },
    clusterCount: {
        ...typography.caption,
        marginTop: spacing.sm,
    },

    // Timeline Card
    timelineCard: {
        padding: spacing.lg,
    },
    timelineRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.sm,
    },
    timelineWeek: {
        ...typography.caption,
        width: 80,
    },
    timelineBar: {
        flex: 1,
        height: 8,
        backgroundColor: colors.lightOrchid,
        borderRadius: 4,
        marginHorizontal: spacing.sm,
        overflow: 'hidden',
    },
    timelineBarFill: {
        height: '100%',
        borderRadius: 4,
    },
    timelineSeverity: {
        ...typography.bodySmall,
        fontWeight: '600',
        width: 24,
        textAlign: 'right',
    },
    timelineCount: {
        ...typography.caption,
        width: 30,
        textAlign: 'right',
    },

    // Follow-ups Card
    followupsCard: {
        padding: spacing.lg,
    },
    followupItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: spacing.sm,
    },
    followupIcon: {
        marginRight: spacing.sm,
        marginTop: 2,
    },
    followupText: {
        ...typography.body,
        flex: 1,
    },

    // Disclaimer
    disclaimerCard: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: spacing.sm,
        padding: spacing.md,
        backgroundColor: colors.lightOrchid + '30',
    },
    disclaimerText: {
        ...typography.caption,
        flex: 1,
        fontStyle: 'italic',
    },
});
